// Team quips — pithy, funny, tier-based descriptions shown in the team detail header.
// Tier assignment: Elite = top 3 by EPA, S = top 8, A = 9–20, B = 21–32, C = rest.
// Click the quip in the UI to re-roll.

const QUIPS = {
    Elite: [
        "The final boss. Everyone else is a tutorial.",
        "Doesn't win matches. Presides over them.",
        "At this point the scoreboard is just their personal journal.",
        "If this team were a weather event, it would be classified as a natural disaster.",
        "The benchmark. The standard. The reason everyone else practices.",
        "Came to compete. Stayed to dominate.",
        "Their warm-up is other teams' peak performance.",
        "Physics applies. Strategy is optional.",
        "What happens when preparation and capability have a very successful meeting.",
        "The reason the field was redesigned three years ago. Probably.",
        "Running at cruise control while everyone else is redlining.",
        "Their contingency plan is better than everyone else's best plan.",
        "Left the learning curve in the rearview mirror years ago.",
        "The ceiling they're approaching is the other teams' stratosphere.",
        "Doesn't just play the game. Edits the rulebook in their favor. Legally.",
        "Arrived. Assessed. Conquered. Went home for dinner.",
        "If confidence were scorable, this would be a perfect match.",
        "Has a plan B, C, D, E, and F. Has never needed them.",
        "The apex. Everything else is the food chain.",
        "Not playing against the field. Playing against history.",
        "Their backup strategy is better than your primary one.",
        "Every match is a formality. They already know how it ends.",
        "Efficiency given physical form.",
        "When they show up, everyone else competes for second.",
        "Exceeds expectations by setting their own.",
        "The yardstick by which other teams measure inadequacy.",
        "A masterclass in 'this is how it's done.'",
        "At some point, they stopped competing and started demonstrating.",
        "The reason strategy meetings run long.",
        "What 'optimized' looks like when it's not joking.",
        "Zero unnecessary movements. Zero wasted seconds. Zero mercy.",
        "Makes the impossible look boring through sheer repetition.",
        "The bar. Also the floor for what they consider acceptable.",
        "If preparation were a sport, they'd win that too.",
        "Their ceiling is everyone else's moon.",
        "Operating in a tier that doesn't officially exist.",
        "Technically beatable. Practically? Let us know how that goes.",
        "Sets the tone. Also the tempo. Also the outcome.",
        "The kind of team that makes referees double-check the rules.",
        "When they lose, it becomes a case study.",
        "The gold standard. Aware of this. Completely unbothered.",
        "Everyone is playing checkers. This team archived checkers.",
        "Other teams peak. This team cruises.",
        "The reason the bracket looks inevitable in hindsight.",
        "Wins matches by making the other team play their game.",
        "Not lucky. Operating at a level where luck is irrelevant.",
        "The rest of the field is a warm-up exercise.",
        "Has a contingency for their contingency.",
        "The scoreboard has learned to anticipate them.",
        "Other teams study film. This team makes the film.",
    ],
    S: [
        "The kind of team that makes other teams reconsider their life choices.",
        "Consistently excellent. Annoyingly so.",
        "Does not have bad days. Has 'slightly less impressive' days.",
        "The answer to the question nobody asked but everyone needed.",
        "Would be intimidating if they weren't so smooth about it.",
        "Makes it look easy. Has made it easy. Refuses to be humble about it.",
        "Statistically inevitable. Emotionally unavoidable.",
        "Has a plan for everything. Including your plan.",
        "The standard that makes everyone else feel slightly underdressed.",
        "Reliable enough to build a religion around.",
        "The reference implementation.",
        "Other teams improve. This team refines.",
        "Doesn't reinvent the wheel. Just makes better wheels.",
        "The team you pick first and sleep better for it.",
        "Has a solve for every problem, including the one you didn't tell them about.",
        "A well-oiled machine that's also slightly smug about it.",
        "Consistently finishes what it starts, which is more than most.",
        "Strategy: be very good. Results: consistent with strategy.",
        "Wins more than the odds suggest. The odds have adjusted accordingly.",
        "The kind of execution that makes scouts write things down.",
        "High floor, high ceiling, not particularly humble about either.",
        "Strong. Consistent. Fully aware of both.",
        "Not lucky. Just prepared for outcomes others didn't anticipate.",
        "Delivers on promises, which is rarer than it sounds.",
        "The serious answer to the question posed by the game.",
        "Has solved several problems you didn't know existed.",
        "Performs well enough that people stop checking the live stats.",
        "Zero drama. Maximum output.",
        "The team described as 'scary' in alliance selection.",
        "What 'putting the work in' actually looks like.",
        "Doesn't coast, but could.",
        "Excellent execution of a good plan. The rarest combination.",
        "The kind of team you want on your side and not across from you.",
        "Consistent to a degree that suggests a spreadsheet.",
        "Has seen your strategy before. Has a response ready.",
        "Comfortable operating at capacity while others struggle at 70%.",
        "The team in other teams' strategy sessions. Often unfavorably.",
        "High expectations. Higher outcomes.",
        "Strong enough that even opponents root for them. Begrudgingly.",
        "Above the line. Aware of it. Moving on.",
        "Not flashy. Just correct, repeatedly, at speed.",
        "Comes prepared. Leaves satisfied. Repeat.",
        "The team other teams reference when explaining why they lost.",
        "Capable and efficient. The two things that actually matter.",
        "The execution phase never goes wrong.",
        "Has made peace with being very good at this.",
        "Consistently in the conversation. Usually ending it.",
        "Brings their A-game to every match, which is a high A.",
        "The team that scouts call 'disciplined' with deep respect.",
        "Would have a nemesis if anyone could keep up long enough.",
    ],
    A: [
        "Does the job. Usually on time. Mostly on purpose.",
        "Could've been S-tier. Chose humility.",
        "Reliable in the way that a good appliance is reliable.",
        "Gets it done. Doesn't always get it done quietly.",
        "Competent. Consistent. Criminally underrated in the right bracket.",
        "The kind of dependable that inspires quiet confidence.",
        "Not the hero. The very capable supporting character.",
        "Better than expected. Aware of it, but not obnoxious about it.",
        "Punches at their weight class and sometimes the class above.",
        "The most reliable thing in an unreliable field.",
        "Knows what it's good at. Does that thing.",
        "A solid alliance partner who will not surprise you, in a good way.",
        "Functional excellence without the press release.",
        "Has a plan and executes roughly 80% of it, which is frankly impressive.",
        "The team you pick second and don't regret.",
        "Quiet competence. The most underrated kind.",
        "Produces results. Takes no notes.",
        "Good enough to win. Self-aware enough to know it's close.",
        "Mid-tier in rank, upper-tier in professionalism.",
        "Has figured most of it out. Working on the rest.",
        "The team that performs exactly as advertised. No more, no less.",
        "Solid. The word 'solid.' Nothing wrong with that.",
        "Operates well under pressure, which is most of the time.",
        "Has earned their seed through quiet, consistent effort.",
        "Not flashy. Has results anyway.",
        "Capable enough that the outcome is rarely a surprise.",
        "One good match away from making everyone reconsider.",
        "Executes its strategy. The strategy is good, actually.",
        "The unsung part of someone's winning bracket.",
        "A known quantity. Comfortably so.",
        "Upper half. Aware of it. Quietly working on the other half.",
        "Produces value without seeking recognition. The ideal teammate.",
        "The team that makes alliance captains say 'yeah, okay, them.'",
        "Has strengths. Knows what they are. Uses them.",
        "Better than their ranking suggests, and their ranking is fine.",
        "Competent in a field where competence is not guaranteed.",
        "Brings something real to the table. The table is grateful.",
        "Steady. In a sport that rewards steady.",
        "An honest reflection of what consistent effort produces.",
        "Reliable enough to plan around. Dangerous enough to notice.",
        "Works hard. It shows. They don't mention it.",
        "The team that wins the rounds other teams dismiss.",
        "Never the biggest story. Often the deciding factor.",
        "The draft pick that ages well.",
        "Performs. Occasionally exceeds. Never embarrasses.",
        "Gets it done in a workmanlike way that deserves more respect.",
        "Has played enough matches to know what they're doing.",
        "The steady hand on the wheel in a turbulent bracket.",
        "Above average in a field where average is still competing.",
        "The team that makes the final match competitive.",
    ],
    B: [
        "Technically present. Spiritually somewhere else.",
        "Has good matches. Also has the other kind.",
        "The embodiment of 'there's always next year,' except it's this year.",
        "Competing enthusiastically, if not always effectively.",
        "A cautionary tale and an inspiration, depending on the match.",
        "Optimistic. Not always justified. Still optimistic.",
        "The middle of the pack. A very crowded, very relatable place.",
        "Has potential. Is working on actualizing it.",
        "Not all heroes wear capes. Not all heroes win consistently either.",
        "The team that tries really hard and occasionally that's enough.",
        "Has a strategy. Execution is a work in progress.",
        "Good enough to matter. Not always consistent enough to capitalize.",
        "Has had great matches. Is due for another one.",
        "Gives 100%. Results are not always proportional to effort.",
        "The participation that makes the field interesting.",
        "Roughly average in a sport where average is still impressive.",
        "Progress is being made. Direction is occasionally uncertain.",
        "Not the alliance captain. Not unimportant. Somewhere in between.",
        "Has moments of brilliance surrounded by context.",
        "Competent enough to be dangerous, inconsistent enough to be risky.",
        "The team you keep an eye on, just in case.",
        "Shows up, competes, learns things. The full experience.",
        "The compelling C plot in a tournament full of A plots.",
        "Tries. It counts.",
        "Has not peaked yet. Very much still working on that.",
        "Might surprise you. Has surprised themselves.",
        "The team that reviews their own footage with complicated feelings.",
        "Battling the gap between vision and execution, in real time.",
        "Has everything it needs. Some assembly still required.",
        "The comeback arc is loading.",
        "A solid foundation. The house is getting there.",
        "Competitive in bursts. Consistent in effort.",
        "Makes up for inconsistency with enthusiasm.",
        "Giving it everything. Everything is being returned slowly.",
        "The kind of team you root for but don't bet on.",
        "Has not found their ceiling yet. Still building the ladder.",
        "Mid-table. A fine table. Well-constructed table.",
        "Knows what needs improving. Improvement is ongoing.",
        "The team for whom 'it's complicated' covers a lot of ground.",
        "In the building. Working on the metaphorical part.",
        "Competitive. Adjacent to dominant. Working on the distance.",
        "Every match is a learning opportunity. They are very educated.",
        "Good at parts. Still assembling the whole.",
        "Has the right idea. Running slightly behind the execution.",
        "The kind of team that makes late-event upsets happen. Sometimes.",
        "Playing with purpose. Purpose is occasionally unclear to observers.",
        "Not the strongest alliance pick. Not the worst decision.",
        "Competitive enough to be a factor. Not yet reliably so.",
        "The most honest reflection of a team that keeps showing up.",
        "Somewhere between 'getting there' and 'there.' Closer than last week.",
        // --- additional 50: graduated from "almost A" toward "almost C" ---
        "Improvement is not a straight line. This team is living proof.",
        "The gap between intent and outcome is narrowing. Slowly.",
        "Has a highlight reel that requires significant context.",
        "Half the field envies their ambition. The other half has seen their execution.",
        "Not in last place. That's something.",
        "The definition of 'making it work.'",
        "Playing their own game. The rules are still being finalized.",
        "Has a plan B for when plan A doesn't work. Plan B often doesn't work either.",
        "A team that peaks at exactly the right time. That time is not yet confirmed.",
        "The story isn't over. They're writing the middle part right now.",
        "Competed hard. Results: contested.",
        "Has figured out some of it. Actively figuring out the rest.",
        "The team whose performance graph would confuse a statistician.",
        "Not quite where they want to be. Closer than they were.",
        "Progress over perfection. Perfection remains elusive.",
        "The textbook definition of 'competitive spirit.'",
        "Has won matches. Plans to remember how.",
        "Inconsistency is a form of mystery. They are mysterious.",
        "Greater than the sum of their parts. On some matches.",
        "The comeback story is still being outlined.",
        "Somewhere in the pack. Specifically: this part of the pack.",
        "Has had their best match. Expecting another one.",
        "Strong in patches. Working on the connecting tissue.",
        "Not winning every match. Winning some of them.",
        "The dark horse that hasn't fully galloped yet.",
        "Capable of more. Occasionally delivering it.",
        "Playing in the bracket they earned. Working on the next one.",
        "Not the favorite. Not not-a-factor either.",
        "A team in motion. Direction occasionally debatable.",
        "The middle of any story is the most interesting part.",
        "Currently managing expectations. Including their own.",
        "The 'wait and see' team. Still waiting. Still seeing.",
        "Brings energy. Results are negotiating terms with the energy.",
        "On the radar. On the fringes of the radar.",
        "Their floor and ceiling are closer together than ideal. Working on the gap.",
        "The team you take a chance on. Chances have variable outcomes.",
        "Average in ways that are genuinely impressive in this company.",
        "Currently in a developmental arc. Development is active.",
        "Has made opponents work for it. Some of them.",
        "The team that makes the bracket interesting without dominating it.",
        "Consistent in effort. Inconsistent in translation.",
        "A team defined more by the journey than the destination. So far.",
        "Has vision. Has a robot. Closing the distance between the two.",
        "The field is better for their presence. The standings are complicated by it.",
        "Has a robot. The robot does things. Some things are useful.",
    ],
    C: [
        "Building character, one match at a time.",
        "Here for the experience. Getting a lot of it.",
        "The sport needs participants. This team is participating.",
        "Every match is an adventure. Some adventures are character-building.",
        "Not winning. But committing to the bit.",
        "Has a lot of heart. Heart is not the limiting factor.",
        "The underdog story hasn't finished loading yet.",
        "Showing up is half the battle. They've got that half.",
        "More optimistic than the record suggests, which is admirable.",
        "Doing their best. Their best and the scoreboard have not yet aligned.",
        "Making memories. Making adjustments. Mostly making memories.",
        "The comeback doesn't happen without the setup. This is the setup.",
        "Technically competing. Points-wise: learning.",
        "Has a lot of room to grow and is actively using it.",
        "The field's most dedicated students of what not to do.",
        "Giving 100% to a task that currently requires more than 100%.",
        "The participation that makes everyone else feel better about their day.",
        "Working through some things. On the field. Publicly.",
        "The origin story is rough but the character arc is compelling.",
        "Every great team was once a team having this kind of event.",
        "Not the best. Not quitting. Both matter.",
        "Has not let results define their enthusiasm. Admirable, actually.",
        "Currently in the 'this is fine' phase of development.",
        "A reminder that showing up is worth something.",
        "The record doesn't capture the effort. Nothing could.",
        "Competing at the edge of their capabilities. The right place to be.",
        "Finding out what works through elimination. Progress!",
        "Currently losing with dignity, which is harder than it sounds.",
        "The long game is long. They're playing it.",
        "Below the median but above 'gave up,' which is the more important line.",
        "The future version of this team is going to be great. Hang tight.",
        "Has data. Is processing it. Outcomes pending.",
        "Persistently present despite contradictory evidence.",
        "The most reliable source of 'wait, really?' moments.",
        "Every expert was once a beginner. Every champion was once exactly this.",
        "Making peace with the gap between expectation and reality.",
        "Things are happening. Some of them are intended.",
        "The season isn't over. The scoreboard disagrees. They don't care.",
        "Collecting losses like other teams collect wins: consistently.",
        "Has the spirit. The execution is still in the mail.",
        "Undaunted. Slightly confused. Undaunted.",
        "Every match teaches them something. It's a masterclass by now.",
        "Here to compete. Competition is teaching them things.",
        "The raw material is there. The refining process is underway.",
        "Currently losing, but thoughtfully.",
        "The results are instructive. They're being instructed.",
        "Representing the noble tradition of 'tried their best.'",
        "Not giving up. Technically ahead of everyone who didn't show up.",
        "Making their own opportunities. Some assembly required.",
        "The underdog. The crowd secretly loves underdogs.",
        // --- additional 50: slightly more graduated from "scrappy-but-close" toward "deeply struggling" ---
        "Has not broken through yet but has broken a lot of things in the attempt.",
        "Every loss is a lesson. They have had a comprehensive curriculum.",
        "The scoreboard is not their friend. They showed up anyway.",
        "Has heart and determination. The translation into points is pending.",
        "The experiment is ongoing. Results will be peer-reviewed eventually.",
        "Finishing the game is harder than starting. They know this now.",
        "The enthusiasm is real. The execution is aspirational.",
        "Fighting for every point. Getting fewer than intended.",
        "The most confident team about how their next match will go.",
        "Has learned more at this event than most people learn in a semester.",
        "The scoreboard is a suggestion. They're exploring that interpretation.",
        "Not winning. Competing. The distinction feels important to them.",
        "Has a robot. The robot has opinions. They're not always helpful.",
        "Currently beta testing their strategy in a live environment.",
        "The 'we'll get 'em next time' energy is strong with this one.",
        "Has contributed to the event in ways that are hard to quantify.",
        "Every great comeback story starts here. Possibly.",
        "The scoreboard is not telling the whole story. The whole story is complicated.",
        "Has more to give. Delivery is TBD.",
        "Competing against physics, time, and the other teams. Mostly losing.",
        "The fact that they're here is both inspiring and statistically surprising.",
        "Has made everyone around them appreciate their own performance more.",
        "Not at their best. Unclear when their best was available for scheduling.",
        "Technically on the field. Impactful in nuanced ways.",
        "Has a lot going on. Coordination is a work in progress.",
        "The team that proves every point matters. By not having very many.",
        "Not done improving. Deeply, urgently not done.",
        "Has survived every match so far. 'Survived' doing a lot of work in that sentence.",
        "The kind of grit you can't teach. You can see it from the stands.",
        "Making the field more interesting through the power of uncertainty.",
        "Going to be a very different team next year. Starting now.",
        "Fighting on multiple fronts. Currently not winning any of them.",
        "The record suggests a team in progress. The team is very much in progress.",
        "Has tried everything. Some things worked briefly.",
        "The definition of a learning experience: this, right here.",
        "Has potential that is visible to the coaching staff and one very optimistic scouter.",
        "Every point is earned the hard way. Points are not often earned.",
        "Has left it all on the field. It may need to be collected.",
        "Has survived the schedule. The schedule has been thorough.",
        "Giving everything. Getting a fraction back. Still giving everything.",
        "The team that scouts describe as 'spirited' when other words escape them.",
        "Currently experiencing what the industry calls 'rapid iteration in production.'",
        "The wins aren't on the board yet. They're storing them for later.",
        "Has ambitions that deserve better hardware. Working on it.",
        "Shows up consistently. The results are not as consistent about showing up.",
        "Has not peaked. Has not approached base camp of their peak.",
        "The season is long. They have a lot of season left.",
        "Somewhere between 'learning the ropes' and 'using the ropes.' The ropes are involved.",
    ],
};

// Tier thresholds on a 0–1 log scale (team EPA vs event min/max).
// logFraction 1.0 = best team, 0.0 = worst team.
export const QUIP_TIERS = [
    { name: 'Elite', min: 0.95 },
    { name: 'S',     min: 0.80 },
    { name: 'A',     min: 0.60 },
    { name: 'B',     min: 0.35 },
    { name: 'C',     min: 0.00 },
];

export function logFractionToTier(logFraction) {
    for (const { name, min } of QUIP_TIERS) {
        if (logFraction >= min) return name;
    }
    return 'C';
}

// Fisher-Yates shuffle driven by a 32-bit LCG (Numerical Recipes constants).
// Returns a shuffled copy of [0, 1, …, length-1].
function lcgShuffle(length, seed) {
    const indices = Array.from({ length }, (_, i) => i);
    let s = seed >>> 0;
    for (let i = length - 1; i > 0; i--) {
        s = ((Math.imul(s, 1664525) + 1013904223) >>> 0);
        const j = s % (i + 1);
        [indices[i], indices[j]] = [indices[j], indices[i]];
    }
    return indices;
}

// Returns a quip for the given team and tier.
// rankInTier: 0-based rank within the tier (sorted by log-fraction descending).
// userSeed:   per-user integer from localStorage — shuffles the pool so every user
//             sees a different assignment while remaining self-consistent.
// randomMode: ignores rank/seed, picks uniformly at random (re-roll button).
export function getTeamQuip(teamNumber, tier, randomMode = false, rankInTier = null, userSeed = 0) {
    const pool = QUIPS[tier] ?? QUIPS['C'];
    if (randomMode) {
        return pool[Math.floor(Math.random() * pool.length)];
    }
    if (rankInTier !== null) {
        // Mix tier identity into seed so each tier gets an independent shuffle
        const tierIdx = QUIP_TIERS.findIndex(t => t.name === tier);
        const seed = ((userSeed >>> 0) ^ (Math.imul(tierIdx + 1, 0x9e3779b9) >>> 0)) >>> 0;
        const shuffled = lcgShuffle(pool.length, seed);
        return pool[shuffled[rankInTier % pool.length]];
    }
    return pool[Number(teamNumber) % pool.length];
}
